# Generated by Django 5.0.7 on 2024-08-22 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HPCLExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=60)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=50)),
                ('session', models.CharField(choices=[('June', 'June'), ('December', 'December')], max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HPCLAnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=30)),
                ('answer', models.CharField(max_length=10)),
                ('paper', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('positive_marks', models.IntegerField(default=0)),
                ('negative_marks', models.IntegerField(default=0)),
                ('HPCLexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpcl.hpclexam')),
            ],
        ),
        migrations.CreateModel(
            name='HPCLExpectedCutOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('jrf', models.CharField(max_length=15)),
                ('assistant_professor', models.CharField(max_length=15)),
                ('HPCLexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpcl.hpclexam')),
            ],
        ),
        migrations.CreateModel(
            name='HPCLStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='admin@margdarshanprep.com', max_length=254)),
                ('mobile', models.IntegerField()),
                ('otp', models.IntegerField()),
                ('email_verify', models.BooleanField(default=0)),
                ('application_no', models.CharField(max_length=50)),
                ('candidate_name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=50)),
                ('test_date', models.CharField(max_length=50)),
                ('test_time', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('total_marks', models.IntegerField(default=0)),
                ('question_attempted', models.IntegerField(default=0)),
                ('correct_question', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=20)),
                ('HPCLexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpcl.hpclexam')),
            ],
        ),
    ]
